name: Google Cloud Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud authentication
        uses: 'google-github-actions/auth@v2'
        with:
           credentials_json: '${{ secrets.ACCOUNT_KEY }}'

      - name: Configure Docker to authenticate to Artifact Registry
        run: |
            gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
            context: .
            push: false
            load: true
            tags: europe-west1-docker.pkg.dev/stellar-stream-458207-t8/isen-python-app/isen-python:latest
            cache-from: type=registry,ref=europe-west1-docker.pkg.dev/stellar-stream-458207-t8/isen-python-app/isen-python:latest
            cache-to: type=inline

      - name: Push Docker image to Artifact Registry
        run: |
            docker push europe-west1-docker.pkg.dev/stellar-stream-458207-t8/isen-python-app/isen-python:latest

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: isen-python-app
          image: europe-west1-docker.pkg.dev/stellar-stream-458207-t8/isen-python-app/isen-python:latest
          region: europe-west9
