name: Build, Push and Scan Docker Image

on:
  push:
    branches:
      - 'branch1'  

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_TOKEN }}  

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:dev-${{ github.sha }}   

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:dev-${{ github.sha }} 

  security-scan:
    needs: docker  
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: "${{ secrets.DOCKER_USERNAME }}/myapp:dev-${{ github.sha }}"  # Référence à l'image Docker construite
          format: "template"
          template: "@/contrib/sarif.tpl"  # Utilisation du modèle SARIF pour le format de sortie
          output: "trivy-results.sarif"  # Fichier SARIF contenant les résultats de la vulnérabilité
          severity: "CRITICAL,HIGH"  # Affichage des résultats pour les vulnérabilités critiques et élevées
           

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"  # Téléchargement du fichier SARIF avec les résultats du scan
