name: Lint Dockerfile

on:
  push:
    branches: [main]
  pull_request:
    
   


jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile  # <-- ici, vérifie que le chemin est bon !
