name: Run Unit and Integration Tests with SAST

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install --upgrade py

      - name: Run unit tests
        run: pytest unit_tests/

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests  # Run after unit tests

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install --upgrade py

      - name: Run integration tests
        run: pytest integration_tests/

  sast:
    name: Static Application Security Testing (SAST) with Bandit
    runs-on: ubuntu-latest
    needs: unit-tests  # Run after unit tests

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit SAST scan
        run: |
          bandit -r . --exclude unit_tests,integration_tests
